import './globals.css'
import { Inter, IBM_Plex_Mono} from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

const IBM = IBM_Plex_Mono({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-IBMPlexMono',
  weight: ["100", "200", "300", "400", "500", "600", "700"],
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${IBM.variable}`}>{children}</body>
    </html>
  )
}
